### ISSUE TITLE
First message is lost when using subscribe/query method

### ISSUE THREAD

**Issue by BharathaAravind** [ecthiender/py-graphql-client#4]
When we set up a subscription the `_start` method is consuming the first message sent by the subscriber which should not be happening. All the messages should be sent to the callback method passed.

The same applies to the `query` method.

**Comment by BharathaAravind** [comment]
I have provided a pull request to fix these issues.
https://github.com/ecthiender/py-graphql-client/pull/3

**Comment by ecthiender** [comment]
Hi @BharathaAravind , thanks for reporting this issue. 

The `_start` method consumes the first message because the reply from the server is supposed to be a `connection_ack` [1]. Which probably is of no interest to the end user. Hence the `_start` message is consuming the `connection_ack` from the server.

Did you face any problem/errors due to this? Can you show me a small example where this was an issue?

[1]: See the [apollo protocol spec for connection_init](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_connection_init)

**Comment by ecthiender** [comment]
@BharathaAravind thanks for reporting this issue.

**Comment by BharathaAravind** [comment]
According to the spec, [https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_connection_init](url)

> GQL_DATA
> The server sends this message to transfer the GraphQL execution result from the server to the client, this message is a response for GQL_START message.
> 
> For each GraphQL operation send with GQL_START, the server will respond with at least one GQL_DATA message.

As per the above guideline the response for the GQL_START will be one or more GQL_DATA.

In the actual implementation of the py-graphql-client. The _start method is consuming the first response and the first message form subscription is lost.
https://github.com/ecthiender/py-graphql-client/blob/master/graphql_client/__init__.py#L48-L53
 ```
def _start(self, payload):
        _id = gen_id()
        frame = {'id': _id, 'type': 'start', 'payload': payload}
        self._conn.send(json.dumps(frame))
        self._conn.recv()
        return _id
```
The change that I have suugested in my pull request referenced in https://github.com/ecthiender/py-graphql-client/pull/3 is:

https://github.com/CIShell/py-graphql-client/blob/master/graphql_client/__init__.py#L48-L52
 ```
def _start(self, payload):
        _id = gen_id()
        frame = {'id': _id, 'type': 'start', 'payload': payload}
        self._conn.send(json.dumps(frame))
        return _id
```

This change would just send the start signal and the wait happens in the subscribe and the first message is not lost.

Please let me know if you need any more details.
